parameters:
  bobv.latex.generator.class: Bobv\LatexBundle\Generator\LatexGenerator
  bobv.latex.generator.locked.class: Bobv\LatexBundle\Generator\LockedLatexGenerator
  bobv.latex.twig.extension.class: Bobv\LatexBundle\Twig\BobvLatexExtension
  bobv.latex.editor.class: Bobv\LatexBundle\Form\Type\LatexType
  bobv.latex.cache_dir: "%kernel.cache_dir%"
  bobv.latex.max_age: -1 day
  bobv.latex.pdflatex.location: "pdflatex"
  bobv.latex.bibliography_binary.location: ""
  bobv.latex.use_symfony_string: false

services:
  Bobv\LatexBundle\Command\LatexTestCommand:
    arguments:
      - "@bobv.latex.generator"
    tags:
      - { name: console.command }

  Bobv\LatexBundle\Generator\LatexGeneratorInterface:
    alias: bobv.latex.generator

  Bobv\LatexBundle\Generator\LockedLatexGeneratorInterface:
    alias: bobv.latex.generator.locked

  bobv.latex.generator:
    class: "%bobv.latex.generator.class%"
    arguments:
      - "%bobv.latex.cache_dir%"
      - "%kernel.environment%"
      - "@twig"
      - "%bobv.latex.max_age%"
      - "%bobv.latex.pdflatex.location%"
      - "%bobv.latex.bibliography_binary.location%"

  bobv.latex.generator.locked:
    class: "%bobv.latex.generator.locked.class%"
    arguments:
      - "@bobv.latex.generator"

  bobv.latex.twig.extension:
    class: "%bobv.latex.twig.extension.class%"
    arguments:
      - "%bobv.latex.use_symfony_string%"
    tags:
      - { name: twig.extension }

  bobv.latex.editor:
    class: "%bobv.latex.editor.class%"
    tags:
      - { name: form.type, alias: bobv_latex }
